#!/usr/bin/env bash
# run_d_vlm.sh — D ablation: VLM-anchor CoGEO attack + eval.
#
# Per (VLM, CLIP_BACKBONE) cell:
#   1. Read captions JSON for this VLM (must have been generated by
#      n3_vlm_caption.py earlier; this script does NOT regenerate captions).
#   2. Run CoGEO attack with --anchor-mode vlm and --vlm-captions-json <FILE>.
#   3. Run eval_harness.py --mode rank against the resulting img/ directory
#      using the SAME CLIP_BACKBONE (in-backbone eval; transfer is run by
#      run_c_transfer.sh).
#
# Inputs (env):
#   VLM            qwen25 | qwen2 | blip
#   CAPTIONS_JSON  path to {asin: caption} JSON for $VLM
#   BACKBONE       short backbone tag (matches n3_attack.py registry)
#   RUN_ROOT       output root (will create $RUN_ROOT/cogeo/ + $RUN_ROOT/eval/)
#   MANIFEST       ESCI manifest.csv
#   IMG_DIR        original image dir
#   GPU            CUDA index
#
# Optional (env):
#   EPS=16 ALPHA=4 ITERS=200 IMAGE_SIZE=224 SKIP_DONE=1

set -euo pipefail

CODE_DIR="${CODE_DIR:-${PROJECT_ROOT}/src}"
VLM="${VLM:?VLM required (qwen25|qwen2|blip)}"
CAPTIONS_JSON="${CAPTIONS_JSON:?CAPTIONS_JSON required}"
BACKBONE="${BACKBONE:?BACKBONE required}"
RUN_ROOT="${RUN_ROOT:?RUN_ROOT required}"
MANIFEST="${MANIFEST:?MANIFEST required}"
IMG_DIR="${IMG_DIR:?IMG_DIR required}"
GPU="${GPU:-0}"
EPS="${EPS:-16}"
ALPHA="${ALPHA:-4}"
ITERS="${ITERS:-200}"
IMAGE_SIZE="${IMAGE_SIZE:-224}"
SKIP_DONE="${SKIP_DONE:-1}"

mkdir -p "$RUN_ROOT"
META="$RUN_ROOT/cell_meta.json"
cat > "$META" <<META
{
  "kind": "D_vlm_ablation",
  "vlm": "$VLM",
  "captions_json": "$CAPTIONS_JSON",
  "run_root": "$RUN_ROOT",
  "manifest": "$MANIFEST",
  "img_dir": "$IMG_DIR",
  "clip_backbone": "$BACKBONE",
  "eps": $EPS,
  "alpha": $ALPHA,
  "image_size": $IMAGE_SIZE,
  "iters": $ITERS,
  "gpu": $GPU,
  "started_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
META

source ${CONDA_BASE}/etc/profile.d/conda.sh
conda activate ${CONDA_ENV:-honestvgeo}
export HF_ENDPOINT="https://hf-mirror.com"
export PYTHONUNBUFFERED=1
export TOKENIZERS_PARALLELISM=false
export CUDA_VISIBLE_DEVICES="$GPU"

cd "$CODE_DIR"

odir="$RUN_ROOT/cogeo"
if [[ "$SKIP_DONE" == "1" && -f "$odir/attack_summary.json" ]]; then
  echo "[d_vlm] SKIP attack cogeo (already done at $odir)"
else
  echo "[d_vlm] === ATTACK cogeo vlm=$VLM bb=$BACKBONE ==="
  python n3_attack.py \
    --method cogeo \
    --manifest "$MANIFEST" \
    --img-dir "$IMG_DIR" \
    --out-dir "$odir" \
    --eps "$EPS" --alpha "$ALPHA" --iters "$ITERS" \
    --clip-backbone "$BACKBONE" \
    --image-size "$IMAGE_SIZE" \
    --anchor-mode vlm \
    --vlm-captions-json "$CAPTIONS_JSON" \
    --gpu 0
fi

edir="$RUN_ROOT/eval"
mkdir -p "$edir"
if [[ "$SKIP_DONE" == "1" && -f "$edir/rank_cogeo_vlm_${VLM}_summary.json" ]]; then
  echo "[d_vlm] SKIP eval-cogeo (already done)"
else
  echo "[d_vlm] === EVAL cogeo vlm=$VLM bb=$BACKBONE ==="
  python eval_harness.py \
    --mode rank \
    --manifest "$MANIFEST" \
    --img-dir "$IMG_DIR" \
    --out-dir "$edir" \
    --adv-dir "$odir/img" \
    --method-tag "cogeo_vlm_${VLM}" \
    --clip-backbone "$BACKBONE" \
    --gpu 0
fi

VLM="$VLM" RUN_ROOT="$RUN_ROOT" BACKBONE="$BACKBONE" python - <<'PY'
import json, os, glob
root = os.environ["RUN_ROOT"]
vlm = os.environ["VLM"]
bb = os.environ["BACKBONE"]
asum_p = os.path.join(root, "cogeo", "attack_summary.json")
esum_p = os.path.join(root, "eval", f"rank_cogeo_vlm_{vlm}_summary.json")
if not os.path.exists(esum_p):
    matches = sorted(glob.glob(os.path.join(root, "eval", "rank_cogeo_vlm_*_summary.json")))
    if matches:
        esum_p = matches[-1]
out = {
    "kind": "D_vlm_ablation",
    "vlm": vlm,
    "clip_backbone": bb,
    "attack_summary": json.load(open(asum_p)) if os.path.exists(asum_p) else None,
    "rank_summary":   json.load(open(esum_p)) if os.path.exists(esum_p) else None,
}
open(os.path.join(root, "cell_summary.json"), "w").write(json.dumps(out, indent=2))
print("cell summary written:", os.path.join(root, "cell_summary.json"))
PY

echo "[d_vlm] DONE $RUN_ROOT"
